[package]
name    = "backend-lib"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
openlifter-common = { path = "../common" }
axum              = { workspace = true }
tokio             = { workspace = true, features = ["full"] }
tower-http        = { workspace = true }
tower             = { version = "0.4", features = ["util"] }
tracing           = { workspace = true }
tracing-subscriber = { workspace = true }
serde             = { workspace = true }
serde_json        = { workspace = true }
dashmap           = { workspace = true }
uuid              = { workspace = true }
scrypt            = { workspace = true }
rand              = { workspace = true }
anyhow            = { workspace = true }
thiserror         = { workspace = true }
futures-util      = { workspace = true }
hyper             = { workspace = true }
async-trait       = "0.1"
config            = "0.13"
figment           = "0.10"
zeroize           = "1.7"
metrics           = "0.21"
metrics-exporter-prometheus = "0.12"
log               = "0.4"

[dev-dependencies]
tempfile = { workspace = true }
tokio    = { workspace = true, features = ["full"] }
tower    = { workspace = true } 