[target.'cfg(all())']
rustflags = [
    "-Dwarnings",
    "-Wclippy::all",
    "-Wclippy::pedantic",
    "-Aclippy::module_name_repetitions",
    "-Aclippy::similar_names",
    "-Aclippy::must_use_candidate",
    "-Aclippy::missing_errors_doc",
    "-Aclippy::missing_panics_doc",
] 