[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"

[dev-dependencies]
serde_json = { version = "1", features = ["raw_value"] }
