# OpenLifter WebSocket Server - Main Configuration File
# Used by the server-core server to configure all functionality

# Server configuration
[server]
host = "127.0.0.1"
port = 3000

# Storage settings
[storage]
path = "data"

# Rate limiting
[rate_limit]
window_secs = 60
max_requests = 100 