[package]
name = "backend-bin"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
backend-lib = { path = "../backend-lib" }
tokio = { workspace = true }
axum = { workspace = true }
tracing-subscriber.workspace = true
